import type { Metadata } from "next";

import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";




const montserrat = Montserrat({
  weight: ["400", "700"], // Medium (400), Bold (700)
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <Header/>
      <body
        className={` ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}